/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentanalytics;

/**
 *
 * @author paraschhabra
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        list1.addItem("bjbjj");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        parentPanel1 = new javax.swing.JPanel();
        chart3_List1 = new javax.swing.JPanel();
        chart1_List1 = new javax.swing.JPanel();
        chart2_List1 = new javax.swing.JPanel();
        PieChartMF = new javax.swing.JPanel();
        list1 = new javax.swing.JComboBox();
        buttonTR = new javax.swing.JButton();
        pieChart_Country = new javax.swing.JPanel();
        parentPanel2 = new javax.swing.JPanel();
        chart1_List2 = new javax.swing.JPanel();
        chart2_List2 = new javax.swing.JPanel();
        chart3_List2 = new javax.swing.JPanel();
        buttonLR = new javax.swing.JButton();
        list2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Al Bayan", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("DASHBOARD");

        parentPanel1.setBackground(new java.awt.Color(255, 255, 255));
        parentPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 204)));
        parentPanel1.setLayout(new java.awt.CardLayout());

        chart3_List1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart3_List1Layout = new javax.swing.GroupLayout(chart3_List1);
        chart3_List1.setLayout(chart3_List1Layout);
        chart3_List1Layout.setHorizontalGroup(
            chart3_List1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        chart3_List1Layout.setVerticalGroup(
            chart3_List1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        parentPanel1.add(chart3_List1, "card4");

        chart1_List1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout chart1_List1Layout = new javax.swing.GroupLayout(chart1_List1);
        chart1_List1.setLayout(chart1_List1Layout);
        chart1_List1Layout.setHorizontalGroup(
            chart1_List1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        chart1_List1Layout.setVerticalGroup(
            chart1_List1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        parentPanel1.add(chart1_List1, "card3");

        chart2_List1.setBackground(new java.awt.Color(204, 51, 255));

        javax.swing.GroupLayout chart2_List1Layout = new javax.swing.GroupLayout(chart2_List1);
        chart2_List1.setLayout(chart2_List1Layout);
        chart2_List1Layout.setHorizontalGroup(
            chart2_List1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        chart2_List1Layout.setVerticalGroup(
            chart2_List1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        parentPanel1.add(chart2_List1, "card2");

        PieChartMF.setBackground(new java.awt.Color(255, 255, 255));
        PieChartMF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout PieChartMFLayout = new javax.swing.GroupLayout(PieChartMF);
        PieChartMF.setLayout(PieChartMFLayout);
        PieChartMFLayout.setHorizontalGroup(
            PieChartMFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        PieChartMFLayout.setVerticalGroup(
            PieChartMFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        list1.setBackground(new java.awt.Color(255, 255, 255));
        list1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Proportion by Country Bar Chart", "Enrolled Number by Year ", "Item", "Item 4" }));
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        buttonTR.setText("Select");
        buttonTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTRActionPerformed(evt);
            }
        });

        pieChart_Country.setBackground(new java.awt.Color(255, 255, 255));
        pieChart_Country.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout pieChart_CountryLayout = new javax.swing.GroupLayout(pieChart_Country);
        pieChart_Country.setLayout(pieChart_CountryLayout);
        pieChart_CountryLayout.setHorizontalGroup(
            pieChart_CountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        pieChart_CountryLayout.setVerticalGroup(
            pieChart_CountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        parentPanel2.setBackground(new java.awt.Color(255, 255, 255));
        parentPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 204, 204)));
        parentPanel2.setLayout(new java.awt.CardLayout());

        chart1_List2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart1_List2Layout = new javax.swing.GroupLayout(chart1_List2);
        chart1_List2.setLayout(chart1_List2Layout);
        chart1_List2Layout.setHorizontalGroup(
            chart1_List2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        chart1_List2Layout.setVerticalGroup(
            chart1_List2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        parentPanel2.add(chart1_List2, "card4");

        chart2_List2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart2_List2Layout = new javax.swing.GroupLayout(chart2_List2);
        chart2_List2.setLayout(chart2_List2Layout);
        chart2_List2Layout.setHorizontalGroup(
            chart2_List2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        chart2_List2Layout.setVerticalGroup(
            chart2_List2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        parentPanel2.add(chart2_List2, "card3");

        chart3_List2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart3_List2Layout = new javax.swing.GroupLayout(chart3_List2);
        chart3_List2.setLayout(chart3_List2Layout);
        chart3_List2Layout.setHorizontalGroup(
            chart3_List2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        chart3_List2Layout.setVerticalGroup(
            chart3_List2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        parentPanel2.add(chart3_List2, "card2");

        buttonLR.setText("Select");
        buttonLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLRActionPerformed(evt);
            }
        });

        list2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pieChart_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(PieChartMF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(list2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLR, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(list1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTR, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(parentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTR, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PieChartMF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLR)
                    .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pieChart_Country, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTRActionPerformed
          switch (list1.getSelectedIndex()){                 // using JCombobox to allow user to select different queries
            case 0:
                parentPanel1.removeAll();
                parentPanel1.add(chart1_List1);
                parentPanel1.repaint();
                parentPanel1.revalidate();
                break;
            case 1:
                parentPanel1.removeAll();
                parentPanel1.add(chart2_List1);
                parentPanel1.repaint();
                parentPanel1.revalidate();
                break;
            case 2:
                parentPanel1.removeAll();
                parentPanel1.add(chart3_List1);
                parentPanel1.repaint();
                parentPanel1.revalidate();
                break;
            
               
        }   
          
    }//GEN-LAST:event_buttonTRActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed
    
    private void buttonLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLRActionPerformed
        switch (list2.getSelectedIndex()){                 // using JCombobox to allow user to select different queries
            case 0:
                parentPanel2.removeAll();
                parentPanel2.add(chart1_List2);
                parentPanel2.repaint();
                parentPanel2.revalidate();
                break;
            case 1:
                parentPanel2.removeAll();
                parentPanel2.add(chart2_List2);
                parentPanel2.repaint();
                parentPanel2.revalidate();
                break;
            case 2:
                parentPanel2.removeAll();
                parentPanel2.add(chart3_List2);
                parentPanel2.repaint();
                parentPanel2.revalidate();
                break;
            
               
        }   
    }//GEN-LAST:event_buttonLRActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PieChartMF;
    private javax.swing.JButton buttonLR;
    private javax.swing.JButton buttonTR;
    private javax.swing.JPanel chart1_List1;
    private javax.swing.JPanel chart1_List2;
    private javax.swing.JPanel chart2_List1;
    private javax.swing.JPanel chart2_List2;
    private javax.swing.JPanel chart3_List1;
    private javax.swing.JPanel chart3_List2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox list1;
    private javax.swing.JComboBox list2;
    private javax.swing.JPanel parentPanel1;
    private javax.swing.JPanel parentPanel2;
    private javax.swing.JPanel pieChart_Country;
    // End of variables declaration//GEN-END:variables
}
